"""
    Create Spotify Playlist with Top 100 Songs of Specific Date
"""
import os
import dotenv
import re
import requests
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from bs4 import BeautifulSoup

dotenv.load_dotenv()

CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRETE = os.getenv("CLIENT_SECRETE")

url = "https://www.billboard.com/charts/hot-100/"
cmd = ""
while re.search("(^19[0-9]{2}-((0[1-9])|(1[0-2]))-((0[1-9])|([1-2][0-9])|(3[0-1]))$)"
                "|(^20(([0-1][0-9])|(2[0-3]))-((0[1-9])|(1[0-2]))-((0[1-9])|([1-2][0-9])|(3[0-1]))$)", cmd) is None:
    cmd = input("Which year you want to travel to? Date YYYY-MM-DD: ")

response = requests.get(url + cmd)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")
song_tag = soup.select(selector="li.lrv-u-width-100p h3")
song_artists_tiles = [(song.find_next_sibling("span").get_text().strip(), song.get_text().strip()) for song in song_tag]

sp = spotipy.Spotify(
    auth_manager=SpotifyOAuth(
        scope="playlist-modify-private",
        redirect_uri="http://example.com",
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRETE,
        show_dialog=True,
        cache_path="token.txt",
        # username="Lucas Sipos",
    )
)
user_id = sp.current_user()["id"]

# Create a playlist for a user
playlist = sp.user_playlist_create(
    user=user_id,
    name=f"{cmd} Billboard 100",
    public=False,
    description="Generated by python program made by https://github.com/Sipos-Lucas-George"
)

song_uris = []
year = cmd.split("-")[0]
for song in song_artists_tiles:
    result = sp.search(q=f"track:{song[1]} year:{year}", type="track")
    try:
        uri = result["tracks"]["items"][0]["uri"]
        song_uris.append(uri)
    except IndexError:
        print(f"{song} doesn't exist in Spotify. Skipped.")

sp.playlist_add_items(playlist_id=playlist["id"], items=song_uris)
