"""
    Creates a New Playlist For Loved Songs
"""
import os
import dotenv
import spotipy
from spotipy.oauth2 import SpotifyOAuth

dotenv.load_dotenv()

CLIENT_ID = os.getenv("CLIENT_ID")
CLIENT_SECRETE = os.getenv("CLIENT_SECRETE")

# Until line 45, saves all URIs in a text file
# uris = []
#
#
# def add_tracks(results):
#     for item in results['items']:
#         track = item['track']
#         uris.append(track['uri'])


# sp = spotipy.Spotify(
#     auth_manager=SpotifyOAuth(
#         scope="user-library-read",
#         redirect_uri="http://example.com",
#         client_id=CLIENT_ID,
#         client_secret=CLIENT_SECRETE,
#         show_dialog=True,
#         cache_path="token.txt",
#     )
# )
# user_id = sp.current_user()["id"]

# results = sp.current_user_saved_tracks()
# add_tracks(results)
#
# while results['next']:
#     results = sp.next(results)
#     add_tracks(results)
#
# with open("uris.txt", "w") as file:
#     for uri in uris:
#         file.write(uri + "\n")

# Create the new playlist with saved songs
with open("uris.txt") as file:
    uris = file.read().split("\n")

sp = spotipy.Spotify(
    auth_manager=SpotifyOAuth(
        scope="playlist-modify-public",
        redirect_uri="http://example.com",
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRETE,
        show_dialog=True,
        cache_path="token.txt",
    )
)
user_id = sp.current_user()["id"]

playlist = sp.user_playlist_create(
    user=user_id,
    name="Loved Songs",
    public=True,
    description="Generated by python program made by https://github.com/Sipos-Lucas-George"
)

for i in range(11):
    sp.playlist_add_items(playlist_id=playlist["id"], items=uris[100*i:100*(i+1)])
sp.playlist_add_items(playlist_id=playlist["id"], items=uris[-86:])
